// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppConfig = { redis_url: string, hub_url: string, connection_token: string, audio_input_device: string | null, audio_output_device: string | null, ptt_hotkey: string, };
