// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppConfig = { redis_url: string, hub_url: string, 
/**
 * Existing M4 field, unused in M10 — intentionally not exposed in the
 * Connection tab UI (FR-007/E4). Preserved through Save round-trips.
 */
connection_token: string, audio_input_device: string | null, audio_output_device: string | null, 
/**
 * "" = never configured (sentinel). The Hotkeys tab shows the first-run
 * prompt and startup registration is skipped (FR-012/A2). M5's "F13"
 * default is gone — configs that explicitly saved a key keep it on load.
 */
ptt_hotkey: string, 
/**
 * M5 personality — five OCEAN traits, each 1–5 (default 3). Written to the
 * hub via Redis `hub:config:personality`.
 * `serde(default)` so pre-M5 saved configs (without these fields) still load.
 */
openness: number, warmth: number, energy: number, conscientiousness: number, assertiveness: number, 
/**
 * M10 LLM config. baseUrl + model propagate to the hub via the Redis
 * `hub:config:llm` key at save time; the API key stays local only.
 */
llm_base_url: string, llm_model: string, 
/**
 * Plain string in the app-data JSON — a known M10 tradeoff (no keychain).
 * Never written to Redis or sent to the hub.
 */
llm_api_key: string, 
/**
 * M10 telemetry logging (US7).
 */
telemetry_logging_enabled: boolean, 
/**
 * "" = unresolved sentinel. `Default::default()` cannot call
 * `app_data_dir()` (no Tauri handle); the startup init flow resolves it to
 * `app_data_dir()/logs/telemetry` and persists the resolved path.
 */
telemetry_log_dir: string, 
/**
 * false shows the first-launch LLM-defaults hint (FR-007). Set to true on
 * the first successful explicit Save-button save only — the PTT auto-save
 * in `bind_ptt_hotkey()` must NOT set it (T022/A2).
 */
first_launch_seen: boolean, };
