// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * T019: connectivity test result for the Connection tab's per-service "Test"
 * buttons (contracts/tauri-commands.md).
 */
export type ConnectionTestResult = { service: string, ok: boolean, latencyMs: bigint | null, error: string | null, };
