// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire shape per data-model.md: Options serialize to JSON null (never omitted,
 * never the string "unknown" — the frontend owns display-string mapping).
 */
export type DebugSnapshot = { sessionActive: boolean, sessionId: string | null, fuelRemaining: number | null, currentLap: number | null, trackPosition: number | null, lapTimeDelta: number | null, redisStreamLagMs: bigint | null, hubConnected: boolean | null, redisConnected: boolean, whisperModelLoaded: boolean | null, };
