// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionInfo = { track_name: string, session_type: string, car_name: string, 
/**
 * HH:MM:SS in local time, captured from system clock at emission
 */
wall_clock_time: string, 
/**
 * Player car index; from DriverInfo.DriverCarIdx (root-level) in session YAML
 */
player_car_idx: number, };
