// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelemetryValue } from "./TelemetryValue";
import type { VarType } from "./VarType";

export type TelemetryField = { name: string, description: string, unit: string, var_type: VarType, value: TelemetryValue, };
