// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TelemetryValue = { "Float": number } | { "Double": number } | { "Int": number } | { "Bool": boolean } | { "Bitfield": number } | { "Char": string } | { "FloatArray": Array<number> } | { "IntArray": Array<number> } | "Unavailable";
