// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved audio device that was absent at startup (T014). Recorded in managed
 * state so a late-mounting Audio tab can query it (`get_audio_device_status`,
 * U1 — Tauri events are not replayed) in addition to the live
 * `audio:device-unavailable` event. Also the event payload shape.
 */
export type UnavailableDevice = { deviceType: string, savedName: string, };
