// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transient upload response — testClipUrl is ephemeral, never persisted (B4).
 */
export type VoiceProfileResult = { filename: string, uploadedAt: string, durationSeconds: number, testClipUrl: string, };
