// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted profile state from Redis hub:config:voice-profile (data-model.md).
 */
export type VoiceProfileState = { filename: string, uploadedAt: string, durationSeconds: number, };
